name: Build Vue
on:
  release:
    types: [created]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'SparkleDEV'
          reponame: 'pkmn-favs-game'
          token: ${{ secrets.GITHUB_TOKEN }}
          cname: pkmngame.sparkle.gay
